org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# API "Veille AO" hébergée sur mufi.ma (peut être surchargée en CI via -PapiBase=...)
apiBase=https://mufi.ma/veilleapi/
